" Kalisi
Bundle 'https://github.com/freeo/vim-kalisi'   
" Base16
Plugin 'chriskempson/base16-vim'
" Wombat
Plugin 'michalbachowski/vim-wombat256mod'
" Github
Plugin 'ricardovaleriano/vim-github-theme'
" FlatUI
Plugin 'john2x/flatui.vim'
" JellyX
Plugin 'guns/jellyx.vim'
" Tomorrow
Plugin 'chriskempson/vim-tomorrow-theme'
" Solarized
Plugin 'altercation/vim-colors-solarized'
