" Kalisi
Plug 'freeo/vim-kalisi'
" Base16
Plug 'chriskempson/base16-vim'
" Wombat
Plug 'michalbachowski/vim-wombat256mod'
" Github
Plug 'ricardovaleriano/vim-github-theme'
" FlatUI
Plug 'john2x/flatui.vim'
" JellyX
Plug 'guns/jellyx.vim'
" Tomorrow
Plug 'chriskempson/vim-tomorrow-theme'
" Solarized
Plug 'altercation/vim-colors-solarized'
